/* OTOMATİK ÜRETİLDİ — elle düzenlemeyin.
 * Kaynak: Kleaf-ibb-envanter-kalemleri.xlsx · Üretim: pnpm envanter:uret (scripts/xlsx-to-envanter.ts)
 * 342 kalem · 29 birim · 15 ana grup */

export interface EnvanterGrubu { code: string; name: string; sortOrder: number }

export interface EnvanterKalemi {
  /** İBB birimi (Unit eşleme ipucu) */
  birim: string;
  ad: string;
  veriBirimi: string;
  /** ISO 14064-1 normalize kategori */
  isoKategori: "CAT1" | "CAT2" | "CAT3" | "CAT4" | "CAT1_2" | "CAT3_4" | "KENT";
  grupCode: string;
}

export const ENVANTER_GRUPLARI: readonly EnvanterGrubu[] = [
  { code: "ELEKTRIK", name: "Elektrik tüketimi envanteri", sortOrder: 0 },
  { code: "DOGALGAZ_YAKIT", name: "Doğalgaz ve sabit yakıt tüketimi envanteri", sortOrder: 1 },
  { code: "ARAC_YAKIT", name: "Araç, iş makinesi ve yakıt envanteri", sortOrder: 2 },
  { code: "JENERATOR", name: "Jeneratör yakıt envanteri", sortOrder: 3 },
  { code: "SATIN_MALZEME", name: "Satın alınan malzeme envanteri", sortOrder: 4 },
  { code: "SATIN_HIZMET", name: "Satın alınan hizmet envanteri", sortOrder: 5 },
  { code: "ATIK_BERTARAF", name: "Atık, atık su, tıbbi atık, hafriyat ve bertaraf envanteri", sortOrder: 6 },
  { code: "PERSONEL_ULASIM", name: "Personel ulaşımı ve iş seyahati envanteri", sortOrder: 7 },
  { code: "ETKINLIK_SOSYAL", name: "Etkinlik, kültür, spor, tanıtım ve sosyal hizmet envanteri", sortOrder: 8 },
  { code: "BT_DIJITAL", name: "BT, veri merkezi, elektronik ekipman ve dijital hizmet envanteri", sortOrder: 9 },
  { code: "SOGUTUCU_GAZ", name: "Soğutucu gaz ve yangın söndürme gazı envanteri", sortOrder: 10 },
  { code: "INSAAT_YOL", name: "İnşaat, altyapı, asfalt, beton, çelik ve yol bakım envanteri", sortOrder: 11 },
  { code: "OFIS_IDARI", name: "Kurumsal ofis, evrak, kağıt ve idari faaliyet envanteri", sortOrder: 12 },
  { code: "TOPLU_TASIMA", name: "Toplu taşıma, raylı sistem, terminal ve ulaşım operasyonları envanteri", sortOrder: 13 },
  { code: "PARK_TARIM", name: "Park, bahçe, tarım, peyzaj ve yeşil alan envanteri", sortOrder: 14 },
] as const;

export const ENVANTER_BIRIMLERI: readonly string[] = [
  "Afet İşleri ve Risk Yönetimi DB",
  "Basın Yayın ve Halkla İlişkiler DB",
  "Bilgi İşlem DB",
  "Boğaziçi İmar Md.",
  "Çevre Koruma ve Kontrol DB",
  "Deprem Risk Yönetimi ve Kentsel İyileştirme DB",
  "Destek Hizmetleri DB",
  "Emlak Yönetimi DB",
  "Etüt ve Projeler DB",
  "Gençlik ve Spor Hizmetleri DB",
  "İmar ve Şehircilik DB",
  "İnsan Kaynakları ve Eğitim DB",
  "İtfaiye DB",
  "Kent Tarihi, Tanıtım ve Turizm DB",
  "Kültür, Sanat ve Sosyal İşler DB",
  "Mali Hizmetler DB",
  "Mezarlıklar Daire Başkanlığı",
  "Muhtarlık İşleri DB",
  "Park Bahçe ve Yeşil Alanlar DB",
  "Raylı Sistem DB",
  "Sağlık DB",
  "Satınalma DB",
  "Sosyal Hizmetler DB",
  "Strateji Geliştirme DB",
  "Tarımsal Hizmetler DB",
  "Ulaşım DB",
  "Yazı İşleri ve Kararlar DB",
  "Yol Bakım ve Altyapı Koordinasyon DB",
  "Zabıta Daire Başkanlığı",
] as const;

export const ENVANTER_KALEMLERI: readonly EnvanterKalemi[] = [
  { birim: "Afet İşleri ve Risk Yönetimi DB", ad: "Afet eğitim merkezleri elektrik tüketimi", veriBirimi: "kWh", isoKategori: "CAT2", grupCode: "ELEKTRIK" },
  { birim: "Afet İşleri ve Risk Yönetimi DB", ad: "Afet eğitim merkezleri doğalgaz tüketimi", veriBirimi: "m³", isoKategori: "CAT1", grupCode: "DOGALGAZ_YAKIT" },
  { birim: "Afet İşleri ve Risk Yönetimi DB", ad: "Afet eğitim araçları yakıt tüketimi", veriBirimi: "L dizel / benzin", isoKategori: "CAT1", grupCode: "ARAC_YAKIT" },
  { birim: "Afet İşleri ve Risk Yönetimi DB", ad: "Tatbikat araçları yakıt tüketimi", veriBirimi: "L", isoKategori: "CAT1", grupCode: "ARAC_YAKIT" },
  { birim: "Afet İşleri ve Risk Yönetimi DB", ad: "Mobil afet eğitim araçları elektrik veya yakıt tüketimi", veriBirimi: "kWh / L", isoKategori: "CAT1_2", grupCode: "ELEKTRIK" },
  { birim: "Afet İşleri ve Risk Yönetimi DB", ad: "Afet konteynerleri, geçici hizmet alanları enerji tüketimi", veriBirimi: "kWh", isoKategori: "CAT2", grupCode: "ELEKTRIK" },
  { birim: "Afet İşleri ve Risk Yönetimi DB", ad: "Jeneratör yakıt tüketimi", veriBirimi: "L dizel", isoKategori: "CAT1", grupCode: "JENERATOR" },
  { birim: "Afet İşleri ve Risk Yönetimi DB", ad: "Afet eğitim materyalleri, basılı dokümanlar", veriBirimi: "kg kağıt / adet", isoKategori: "CAT4", grupCode: "SATIN_MALZEME" },
  { birim: "Afet İşleri ve Risk Yönetimi DB", ad: "Tatbikatlarda kullanılan ekipman ve sarf malzemeleri", veriBirimi: "kg / adet", isoKategori: "CAT4", grupCode: "SATIN_HIZMET" },
  { birim: "Afet İşleri ve Risk Yönetimi DB", ad: "Personel saha ulaşımı", veriBirimi: "km / L yakıt", isoKategori: "CAT3", grupCode: "ARAC_YAKIT" },
  { birim: "Afet İşleri ve Risk Yönetimi DB", ad: "Afet tatbikatı kaynaklı atıklar", veriBirimi: "kg / ton", isoKategori: "CAT4", grupCode: "ATIK_BERTARAF" },
  { birim: "Afet İşleri ve Risk Yönetimi DB", ad: "Eğitim organizasyonları için konaklama ve seyahatler", veriBirimi: "km / geceleme", isoKategori: "CAT3", grupCode: "PERSONEL_ULASIM" },
  { birim: "Basın Yayın ve Halkla İlişkiler DB", ad: "Basılı yayınlar", veriBirimi: "adet / kg kağıt", isoKategori: "CAT4", grupCode: "SATIN_MALZEME" },
  { birim: "Basın Yayın ve Halkla İlişkiler DB", ad: "Broşür, afiş, katalog, dergi, kitapçık tüketimi", veriBirimi: "adet / kg", isoKategori: "CAT4", grupCode: "ETKINLIK_SOSYAL" },
  { birim: "Basın Yayın ve Halkla İlişkiler DB", ad: "Tanıtım materyalleri", veriBirimi: "adet / kg", isoKategori: "CAT4", grupCode: "ETKINLIK_SOSYAL" },
  { birim: "Basın Yayın ve Halkla İlişkiler DB", ad: "Baskı hizmeti satın alımları", veriBirimi: "TL / adet / kg", isoKategori: "CAT4", grupCode: "SATIN_HIZMET" },
  { birim: "Basın Yayın ve Halkla İlişkiler DB", ad: "Medya prodüksiyon ekipmanları elektrik tüketimi", veriBirimi: "kWh", isoKategori: "CAT2", grupCode: "ELEKTRIK" },
  { birim: "Basın Yayın ve Halkla İlişkiler DB", ad: "Etkinliklerde kullanılan ses, ışık, ekran sistemleri elektrik tüketimi", veriBirimi: "kWh", isoKategori: "CAT2", grupCode: "ELEKTRIK" },
  { birim: "Basın Yayın ve Halkla İlişkiler DB", ad: "Saha çekim araçları yakıt tüketimi", veriBirimi: "L", isoKategori: "CAT1", grupCode: "ARAC_YAKIT" },
  { birim: "Basın Yayın ve Halkla İlişkiler DB", ad: "Fotoğraf/video çekim ekiplerinin ulaşımı", veriBirimi: "km", isoKategori: "CAT3", grupCode: "PERSONEL_ULASIM" },
  { birim: "Basın Yayın ve Halkla İlişkiler DB", ad: "Dijital yayın, web, barındırma, sunucu hizmetleri", veriBirimi: "kWh / hizmet bedeli", isoKategori: "CAT4", grupCode: "BT_DIJITAL" },
  { birim: "Basın Yayın ve Halkla İlişkiler DB", ad: "Basın toplantıları ve organizasyonlardan çıkan atıklar", veriBirimi: "kg / ton", isoKategori: "CAT4", grupCode: "ATIK_BERTARAF" },
  { birim: "Basın Yayın ve Halkla İlişkiler DB", ad: "Kargo ve dağıtım hizmetleri", veriBirimi: "km / ton-km", isoKategori: "CAT3_4", grupCode: "PERSONEL_ULASIM" },
  { birim: "Bilgi İşlem DB", ad: "Veri merkezi elektrik tüketimi", veriBirimi: "kWh", isoKategori: "CAT2", grupCode: "BT_DIJITAL" },
  { birim: "Bilgi İşlem DB", ad: "Sunucu odası elektrik tüketimi", veriBirimi: "kWh", isoKategori: "CAT2", grupCode: "BT_DIJITAL" },
  { birim: "Bilgi İşlem DB", ad: "UPS sistemleri elektrik tüketimi", veriBirimi: "kWh", isoKategori: "CAT2", grupCode: "BT_DIJITAL" },
  { birim: "Bilgi İşlem DB", ad: "Veri merkezi soğutma sistemleri elektrik tüketimi", veriBirimi: "kWh", isoKategori: "CAT2", grupCode: "BT_DIJITAL" },
  { birim: "Bilgi İşlem DB", ad: "Soğutucu gaz kaçakları", veriBirimi: "kg gaz", isoKategori: "CAT1", grupCode: "SOGUTUCU_GAZ" },
  { birim: "Bilgi İşlem DB", ad: "Jeneratör yakıt tüketimi", veriBirimi: "L dizel", isoKategori: "CAT1", grupCode: "JENERATOR" },
  { birim: "Bilgi İşlem DB", ad: "Bilgisayar, laptop, monitör alımları", veriBirimi: "adet", isoKategori: "CAT4", grupCode: "BT_DIJITAL" },
  { birim: "Bilgi İşlem DB", ad: "Sunucu, switch, firewall, network ekipmanı alımları", veriBirimi: "adet", isoKategori: "CAT4", grupCode: "BT_DIJITAL" },
  { birim: "Bilgi İşlem DB", ad: "Yazıcı, tarayıcı, çevre birimleri alımları", veriBirimi: "adet", isoKategori: "CAT4", grupCode: "INSAAT_YOL" },
  { birim: "Bilgi İşlem DB", ad: "Yazılım lisansı ve bulut hizmeti satın alımları", veriBirimi: "TL / hizmet türü", isoKategori: "CAT4", grupCode: "BT_DIJITAL" },
  { birim: "Bilgi İşlem DB", ad: "Elektronik atıklar", veriBirimi: "kg / adet", isoKategori: "CAT4", grupCode: "BT_DIJITAL" },
  { birim: "Bilgi İşlem DB", ad: "Batarya ve UPS akü atıkları", veriBirimi: "kg / adet", isoKategori: "CAT4", grupCode: "BT_DIJITAL" },
  { birim: "Bilgi İşlem DB", ad: "BT bakım-onarım hizmetleri", veriBirimi: "TL / kullanılan parça", isoKategori: "CAT4", grupCode: "BT_DIJITAL" },
  { birim: "Bilgi İşlem DB", ad: "Personel teknik servis saha ulaşımı", veriBirimi: "km / yakıt", isoKategori: "CAT3", grupCode: "ARAC_YAKIT" },
  { birim: "Boğaziçi İmar Md.", ad: "Müdürlük ofis elektrik tüketimi", veriBirimi: "kWh", isoKategori: "CAT2", grupCode: "ELEKTRIK" },
  { birim: "Boğaziçi İmar Md.", ad: "Ofis doğalgaz tüketimi", veriBirimi: "m³", isoKategori: "CAT1", grupCode: "DOGALGAZ_YAKIT" },
  { birim: "Boğaziçi İmar Md.", ad: "Saha denetim araçları yakıt tüketimi", veriBirimi: "L", isoKategori: "CAT1", grupCode: "ARAC_YAKIT" },
  { birim: "Boğaziçi İmar Md.", ad: "İmar inceleme ve denetim seyahatleri", veriBirimi: "km", isoKategori: "CAT3", grupCode: "PERSONEL_ULASIM" },
  { birim: "Boğaziçi İmar Md.", ad: "Proje çıktıları, ozalit, harita, plan baskıları", veriBirimi: "adet / kg kağıt", isoKategori: "CAT4", grupCode: "SATIN_MALZEME" },
  { birim: "Boğaziçi İmar Md.", ad: "Arşivleme ve evrak tüketimi", veriBirimi: "kg kağıt", isoKategori: "CAT4", grupCode: "SATIN_MALZEME" },
  { birim: "Boğaziçi İmar Md.", ad: "Teknik danışmanlık hizmetleri", veriBirimi: "TL", isoKategori: "CAT4", grupCode: "SATIN_HIZMET" },
  { birim: "Boğaziçi İmar Md.", ad: "Ölçüm, analiz ve raporlama hizmetleri", veriBirimi: "TL", isoKategori: "CAT4", grupCode: "SATIN_HIZMET" },
  { birim: "Boğaziçi İmar Md.", ad: "Saha kontrol ekipmanları", veriBirimi: "adet", isoKategori: "CAT4", grupCode: "SATIN_MALZEME" },
  { birim: "Boğaziçi İmar Md.", ad: "Ofis kaynaklı atıklar", veriBirimi: "kg / ton", isoKategori: "CAT4", grupCode: "ATIK_BERTARAF" },
  { birim: "Çevre Koruma ve Kontrol DB", ad: "Katı atık miktarı", veriBirimi: "ton", isoKategori: "CAT4", grupCode: "ATIK_BERTARAF" },
  { birim: "Çevre Koruma ve Kontrol DB", ad: "Evsel atık miktarı", veriBirimi: "ton", isoKategori: "CAT4", grupCode: "ATIK_BERTARAF" },
  { birim: "Çevre Koruma ve Kontrol DB", ad: "Tıbbi atık miktarı", veriBirimi: "ton", isoKategori: "CAT4", grupCode: "ATIK_BERTARAF" },
  { birim: "Çevre Koruma ve Kontrol DB", ad: "Tehlikeli atık miktarı", veriBirimi: "kg / ton", isoKategori: "CAT4", grupCode: "ATIK_BERTARAF" },
  { birim: "Çevre Koruma ve Kontrol DB", ad: "Ambalaj atığı miktarı", veriBirimi: "kg / ton", isoKategori: "CAT4", grupCode: "OFIS_IDARI" },
  { birim: "Çevre Koruma ve Kontrol DB", ad: "Geri dönüşüme gönderilen atıklar", veriBirimi: "ton", isoKategori: "CAT4", grupCode: "ATIK_BERTARAF" },
  { birim: "Çevre Koruma ve Kontrol DB", ad: "Düzenli depolamaya gönderilen atıklar", veriBirimi: "ton", isoKategori: "CAT4", grupCode: "ATIK_BERTARAF" },
  { birim: "Çevre Koruma ve Kontrol DB", ad: "Yakma / enerji geri kazanım tesisine gönderilen atıklar", veriBirimi: "ton", isoKategori: "CAT4", grupCode: "ATIK_BERTARAF" },
  { birim: "Çevre Koruma ve Kontrol DB", ad: "Kompost / biyometanizasyon atıkları", veriBirimi: "ton", isoKategori: "CAT4", grupCode: "ATIK_BERTARAF" },
  { birim: "Çevre Koruma ve Kontrol DB", ad: "Hafriyat toprağı miktarı", veriBirimi: "ton / m³", isoKategori: "CAT4", grupCode: "INSAAT_YOL" },
  { birim: "Çevre Koruma ve Kontrol DB", ad: "İnşaat ve yıkıntı atığı miktarı", veriBirimi: "ton", isoKategori: "CAT4", grupCode: "INSAAT_YOL" },
  { birim: "Çevre Koruma ve Kontrol DB", ad: "Arıtma çamuru", veriBirimi: "ton", isoKategori: "CAT4", grupCode: "ATIK_BERTARAF" },
  { birim: "Çevre Koruma ve Kontrol DB", ad: "Atık taşıma araçları yakıt tüketimi", veriBirimi: "L", isoKategori: "CAT1", grupCode: "ATIK_BERTARAF" },
  { birim: "Çevre Koruma ve Kontrol DB", ad: "Atık aktarma istasyonları elektrik tüketimi", veriBirimi: "kWh", isoKategori: "CAT2", grupCode: "ATIK_BERTARAF" },
  { birim: "Çevre Koruma ve Kontrol DB", ad: "Atık bertaraf tesisleri elektrik/doğalgaz tüketimi", veriBirimi: "kWh / m³", isoKategori: "CAT1_2", grupCode: "ATIK_BERTARAF" },
  { birim: "Çevre Koruma ve Kontrol DB", ad: "Çevre denetim araçları yakıt tüketimi", veriBirimi: "L", isoKategori: "CAT1", grupCode: "ARAC_YAKIT" },
  { birim: "Çevre Koruma ve Kontrol DB", ad: "Numune alma ve laboratuvar hizmetleri", veriBirimi: "TL / numune sayısı", isoKategori: "CAT4", grupCode: "SATIN_HIZMET" },
  { birim: "Çevre Koruma ve Kontrol DB", ad: "Temizlik operasyonlarında kullanılan ekipman ve kimyasallar", veriBirimi: "kg / L", isoKategori: "CAT4", grupCode: "SATIN_HIZMET" },
  { birim: "Deprem Risk Yönetimi ve Kentsel İyileştirme DB", ad: "Bina risk analizi saha ziyaretleri", veriBirimi: "km / yakıt", isoKategori: "CAT3", grupCode: "ARAC_YAKIT" },
  { birim: "Deprem Risk Yönetimi ve Kentsel İyileştirme DB", ad: "Zemin etüdü araçları yakıt tüketimi", veriBirimi: "L", isoKategori: "CAT1", grupCode: "ARAC_YAKIT" },
  { birim: "Deprem Risk Yönetimi ve Kentsel İyileştirme DB", ad: "Sondaj çalışmaları yakıt/elektrik tüketimi", veriBirimi: "L / kWh", isoKategori: "CAT1_2", grupCode: "ELEKTRIK" },
  { birim: "Deprem Risk Yönetimi ve Kentsel İyileştirme DB", ad: "Laboratuvar analiz hizmetleri", veriBirimi: "TL / numune sayısı", isoKategori: "CAT4", grupCode: "SATIN_HIZMET" },
  { birim: "Deprem Risk Yönetimi ve Kentsel İyileştirme DB", ad: "Kentsel dönüşüm proje danışmanlıkları", veriBirimi: "TL", isoKategori: "CAT4", grupCode: "SATIN_HIZMET" },
  { birim: "Deprem Risk Yönetimi ve Kentsel İyileştirme DB", ad: "Yıkım kaynaklı inşaat/yıkıntı atıkları", veriBirimi: "ton", isoKategori: "CAT4", grupCode: "INSAAT_YOL" },
  { birim: "Deprem Risk Yönetimi ve Kentsel İyileştirme DB", ad: "Hafriyat taşıması", veriBirimi: "ton-km", isoKategori: "CAT3", grupCode: "INSAAT_YOL" },
  { birim: "Deprem Risk Yönetimi ve Kentsel İyileştirme DB", ad: "Beton, çelik, yapı malzemesi analizleri", veriBirimi: "kg / ton / TL", isoKategori: "CAT4", grupCode: "INSAAT_YOL" },
  { birim: "Deprem Risk Yönetimi ve Kentsel İyileştirme DB", ad: "Proje ve rapor baskıları", veriBirimi: "kg kağıt / adet", isoKategori: "CAT4", grupCode: "SATIN_MALZEME" },
  { birim: "Deprem Risk Yönetimi ve Kentsel İyileştirme DB", ad: "Ofis enerji tüketimi", veriBirimi: "kWh / m³", isoKategori: "CAT1_2", grupCode: "ELEKTRIK" },
  { birim: "Destek Hizmetleri DB", ad: "Belediye hizmet binaları elektrik tüketimi", veriBirimi: "kWh", isoKategori: "CAT2", grupCode: "ELEKTRIK" },
  { birim: "Destek Hizmetleri DB", ad: "Belediye hizmet binaları doğalgaz tüketimi", veriBirimi: "m³", isoKategori: "CAT1", grupCode: "DOGALGAZ_YAKIT" },
  { birim: "Destek Hizmetleri DB", ad: "Bina jeneratör yakıt tüketimi", veriBirimi: "L dizel", isoKategori: "CAT1", grupCode: "JENERATOR" },
  { birim: "Destek Hizmetleri DB", ad: "Hizmet araçları yakıt tüketimi", veriBirimi: "L", isoKategori: "CAT1", grupCode: "ARAC_YAKIT" },
  { birim: "Destek Hizmetleri DB", ad: "Temizlik hizmeti alımları", veriBirimi: "TL / personel / kullanılan malzeme", isoKategori: "CAT4", grupCode: "PERSONEL_ULASIM" },
  { birim: "Destek Hizmetleri DB", ad: "Güvenlik hizmeti alımları", veriBirimi: "TL", isoKategori: "CAT4", grupCode: "SATIN_HIZMET" },
  { birim: "Destek Hizmetleri DB", ad: "Yemek hizmeti / öğün sayısı", veriBirimi: "adet öğün", isoKategori: "CAT4", grupCode: "ETKINLIK_SOSYAL" },
  { birim: "Destek Hizmetleri DB", ad: "Ofis mobilyası alımları", veriBirimi: "adet / kg", isoKategori: "CAT4", grupCode: "SATIN_MALZEME" },
  { birim: "Destek Hizmetleri DB", ad: "Ofis sarf malzemeleri", veriBirimi: "kg / adet / TL", isoKategori: "CAT4", grupCode: "SATIN_HIZMET" },
  { birim: "Destek Hizmetleri DB", ad: "Bakım-onarım malzemeleri", veriBirimi: "kg / adet / TL", isoKategori: "CAT4", grupCode: "SATIN_HIZMET" },
  { birim: "Destek Hizmetleri DB", ad: "Bina kaynaklı atıklar", veriBirimi: "kg / ton", isoKategori: "CAT4", grupCode: "ATIK_BERTARAF" },
  { birim: "Destek Hizmetleri DB", ad: "Kiralık araç kullanımları", veriBirimi: "km / L yakıt / TL", isoKategori: "CAT3_4", grupCode: "ARAC_YAKIT" },
  { birim: "Destek Hizmetleri DB", ad: "Personel servisleri", veriBirimi: "km / yakıt / kişi", isoKategori: "CAT3", grupCode: "ARAC_YAKIT" },
  { birim: "Emlak Yönetimi DB", ad: "Belediye taşınmazları elektrik tüketimi", veriBirimi: "kWh", isoKategori: "CAT2", grupCode: "ELEKTRIK" },
  { birim: "Emlak Yönetimi DB", ad: "Belediye taşınmazları doğalgaz tüketimi", veriBirimi: "m³", isoKategori: "CAT1", grupCode: "DOGALGAZ_YAKIT" },
  { birim: "Emlak Yönetimi DB", ad: "Kiralanan tesislerin enerji tüketimi", veriBirimi: "kWh / m³", isoKategori: "CAT1_2", grupCode: "ELEKTRIK" },
  { birim: "Emlak Yönetimi DB", ad: "İşletilen sosyal/teknik tesislerin enerji tüketimi", veriBirimi: "kWh / m³", isoKategori: "CAT1_2", grupCode: "ELEKTRIK" },
  { birim: "Emlak Yönetimi DB", ad: "Bina bakım-onarım malzemeleri", veriBirimi: "kg / adet / TL", isoKategori: "CAT4", grupCode: "SATIN_HIZMET" },
  { birim: "Emlak Yönetimi DB", ad: "Tadilat ve yenileme işleri", veriBirimi: "TL / malzeme miktarı", isoKategori: "CAT4", grupCode: "SATIN_HIZMET" },
  { birim: "Emlak Yönetimi DB", ad: "Saha ziyaret araçları yakıt tüketimi", veriBirimi: "L / km", isoKategori: "CAT3", grupCode: "ARAC_YAKIT" },
  { birim: "Emlak Yönetimi DB", ad: "Emlak ekspertiz ve danışmanlık hizmetleri", veriBirimi: "TL", isoKategori: "CAT4", grupCode: "SATIN_HIZMET" },
  { birim: "Emlak Yönetimi DB", ad: "Taşınmazlara ait atıklar", veriBirimi: "kg / ton", isoKategori: "CAT4", grupCode: "ATIK_BERTARAF" },
  { birim: "Emlak Yönetimi DB", ad: "Soğutucu gaz kullanılan tesisler varsa gaz dolumu", veriBirimi: "kg gaz", isoKategori: "CAT1", grupCode: "SOGUTUCU_GAZ" },
  { birim: "Etüt ve Projeler DB", ad: "Proje ofisi elektrik tüketimi", veriBirimi: "kWh", isoKategori: "CAT2", grupCode: "ELEKTRIK" },
  { birim: "Etüt ve Projeler DB", ad: "Proje ofisi doğalgaz tüketimi", veriBirimi: "m³", isoKategori: "CAT1", grupCode: "DOGALGAZ_YAKIT" },
  { birim: "Etüt ve Projeler DB", ad: "Saha ölçüm araçları yakıt tüketimi", veriBirimi: "L / km", isoKategori: "CAT3", grupCode: "ARAC_YAKIT" },
  { birim: "Etüt ve Projeler DB", ad: "Zemin etüdü, ölçüm ve analiz hizmetleri", veriBirimi: "TL / numune", isoKategori: "CAT4", grupCode: "SATIN_HIZMET" },
  { birim: "Etüt ve Projeler DB", ad: "Teknik danışmanlık hizmetleri", veriBirimi: "TL", isoKategori: "CAT4", grupCode: "SATIN_HIZMET" },
  { birim: "Etüt ve Projeler DB", ad: "Proje çıktıları, çizim, rapor, ozalit", veriBirimi: "adet / kg kağıt", isoKategori: "CAT4", grupCode: "SATIN_MALZEME" },
  { birim: "Etüt ve Projeler DB", ad: "Harita, plan, teknik doküman baskıları", veriBirimi: "adet / kg", isoKategori: "CAT4", grupCode: "OFIS_IDARI" },
  { birim: "Etüt ve Projeler DB", ad: "Ölçüm cihazları ve teknik ekipman alımları", veriBirimi: "adet", isoKategori: "CAT4", grupCode: "SATIN_MALZEME" },
  { birim: "Etüt ve Projeler DB", ad: "Saha çalışması kaynaklı atıklar", veriBirimi: "kg", isoKategori: "CAT4", grupCode: "ATIK_BERTARAF" },
  { birim: "Etüt ve Projeler DB", ad: "Toplantı ve çalıştay organizasyonları", veriBirimi: "kişi / km / tüketim", isoKategori: "CAT3_4", grupCode: "PERSONEL_ULASIM" },
  { birim: "Gençlik ve Spor Hizmetleri DB", ad: "Spor tesisleri elektrik tüketimi", veriBirimi: "kWh", isoKategori: "CAT2", grupCode: "ELEKTRIK" },
  { birim: "Gençlik ve Spor Hizmetleri DB", ad: "Spor tesisleri doğalgaz tüketimi", veriBirimi: "m³", isoKategori: "CAT1", grupCode: "DOGALGAZ_YAKIT" },
  { birim: "Gençlik ve Spor Hizmetleri DB", ad: "Yüzme havuzu ısıtma enerjisi", veriBirimi: "kWh / m³ doğalgaz", isoKategori: "CAT1_2", grupCode: "ELEKTRIK" },
  { birim: "Gençlik ve Spor Hizmetleri DB", ad: "Havuz filtrasyon ve pompa elektrik tüketimi", veriBirimi: "kWh", isoKategori: "CAT2", grupCode: "ELEKTRIK" },
  { birim: "Gençlik ve Spor Hizmetleri DB", ad: "Spor salonu aydınlatma/iklimlendirme tüketimi", veriBirimi: "kWh", isoKategori: "CAT2", grupCode: "ELEKTRIK" },
  { birim: "Gençlik ve Spor Hizmetleri DB", ad: "Açık saha aydınlatmaları", veriBirimi: "kWh", isoKategori: "CAT2", grupCode: "ELEKTRIK" },
  { birim: "Gençlik ve Spor Hizmetleri DB", ad: "Spor ekipmanları alımları", veriBirimi: "adet / kg / TL", isoKategori: "CAT4", grupCode: "ETKINLIK_SOSYAL" },
  { birim: "Gençlik ve Spor Hizmetleri DB", ad: "Etkinlik ulaşımı", veriBirimi: "kişi-km / araç-km", isoKategori: "CAT3", grupCode: "TOPLU_TASIMA" },
  { birim: "Gençlik ve Spor Hizmetleri DB", ad: "Spor organizasyonları atıkları", veriBirimi: "kg / ton", isoKategori: "CAT4", grupCode: "ATIK_BERTARAF" },
  { birim: "Gençlik ve Spor Hizmetleri DB", ad: "Yemek, içecek ve ikram hizmetleri", veriBirimi: "adet / TL", isoKategori: "CAT4", grupCode: "ETKINLIK_SOSYAL" },
  { birim: "Gençlik ve Spor Hizmetleri DB", ad: "Tesis bakım kimyasalları", veriBirimi: "kg / L", isoKategori: "CAT4", grupCode: "SATIN_MALZEME" },
  { birim: "Gençlik ve Spor Hizmetleri DB", ad: "Soğutucu gaz kaçakları", veriBirimi: "kg gaz", isoKategori: "CAT1", grupCode: "SOGUTUCU_GAZ" },
  { birim: "İmar ve Şehircilik DB", ad: "Ofis elektrik tüketimi", veriBirimi: "kWh", isoKategori: "CAT2", grupCode: "ELEKTRIK" },
  { birim: "İmar ve Şehircilik DB", ad: "Ofis doğalgaz tüketimi", veriBirimi: "m³", isoKategori: "CAT1", grupCode: "DOGALGAZ_YAKIT" },
  { birim: "İmar ve Şehircilik DB", ad: "Saha inceleme araçları yakıt tüketimi", veriBirimi: "L / km", isoKategori: "CAT3", grupCode: "ARAC_YAKIT" },
  { birim: "İmar ve Şehircilik DB", ad: "Ruhsat, imar, planlama süreçlerinde kağıt tüketimi", veriBirimi: "kg / adet", isoKategori: "CAT4", grupCode: "SATIN_MALZEME" },
  { birim: "İmar ve Şehircilik DB", ad: "Plan, proje ve harita baskıları", veriBirimi: "adet / kg", isoKategori: "CAT4", grupCode: "OFIS_IDARI" },
  { birim: "İmar ve Şehircilik DB", ad: "Arşivleme hizmetleri", veriBirimi: "TL / kg kağıt", isoKategori: "CAT4", grupCode: "SATIN_HIZMET" },
  { birim: "İmar ve Şehircilik DB", ad: "Teknik danışmanlık hizmetleri", veriBirimi: "TL", isoKategori: "CAT4", grupCode: "SATIN_HIZMET" },
  { birim: "İmar ve Şehircilik DB", ad: "Denetim ve saha kontrol faaliyetleri", veriBirimi: "km", isoKategori: "CAT3", grupCode: "PERSONEL_ULASIM" },
  { birim: "İmar ve Şehircilik DB", ad: "Bilgisayar, yazıcı, tarayıcı ekipmanları", veriBirimi: "adet", isoKategori: "CAT4", grupCode: "BT_DIJITAL" },
  { birim: "İmar ve Şehircilik DB", ad: "Ofis atıkları", veriBirimi: "kg / ton", isoKategori: "CAT4", grupCode: "ATIK_BERTARAF" },
  { birim: "İnsan Kaynakları ve Eğitim DB", ad: "Personel işe geliş-gidiş verileri", veriBirimi: "kişi / km / gün", isoKategori: "CAT3", grupCode: "PERSONEL_ULASIM" },
  { birim: "İnsan Kaynakları ve Eğitim DB", ad: "Personel servis kullanımı", veriBirimi: "km / yakıt / kişi", isoKategori: "CAT3", grupCode: "ARAC_YAKIT" },
  { birim: "İnsan Kaynakları ve Eğitim DB", ad: "Eğitim faaliyetleri ulaşım verileri", veriBirimi: "kişi-km", isoKategori: "CAT3", grupCode: "PERSONEL_ULASIM" },
  { birim: "İnsan Kaynakları ve Eğitim DB", ad: "Şehir dışı eğitim/seyahatler", veriBirimi: "km / yolcu-km", isoKategori: "CAT3", grupCode: "TOPLU_TASIMA" },
  { birim: "İnsan Kaynakları ve Eğitim DB", ad: "Konaklama verileri", veriBirimi: "geceleme", isoKategori: "CAT3", grupCode: "PERSONEL_ULASIM" },
  { birim: "İnsan Kaynakları ve Eğitim DB", ad: "Eğitim salonları elektrik tüketimi", veriBirimi: "kWh", isoKategori: "CAT2", grupCode: "ELEKTRIK" },
  { birim: "İnsan Kaynakları ve Eğitim DB", ad: "Eğitim materyalleri", veriBirimi: "kg kağıt / adet", isoKategori: "CAT4", grupCode: "SATIN_MALZEME" },
  { birim: "İnsan Kaynakları ve Eğitim DB", ad: "Basılı sertifika, kitapçık, dokümanlar", veriBirimi: "adet / kg", isoKategori: "CAT4", grupCode: "OFIS_IDARI" },
  { birim: "İnsan Kaynakları ve Eğitim DB", ad: "Online eğitim platformu/hizmet alımı", veriBirimi: "TL", isoKategori: "CAT4", grupCode: "SATIN_HIZMET" },
  { birim: "İnsan Kaynakları ve Eğitim DB", ad: "Eğitim organizasyonu ikram/yemek hizmetleri", veriBirimi: "adet / TL", isoKategori: "CAT4", grupCode: "ETKINLIK_SOSYAL" },
  { birim: "İtfaiye DB", ad: "İtfaiye araçları dizel tüketimi", veriBirimi: "L", isoKategori: "CAT1", grupCode: "ARAC_YAKIT" },
  { birim: "İtfaiye DB", ad: "İtfaiye istasyonları elektrik tüketimi", veriBirimi: "kWh", isoKategori: "CAT2", grupCode: "ELEKTRIK" },
  { birim: "İtfaiye DB", ad: "İtfaiye istasyonları doğalgaz tüketimi", veriBirimi: "m³", isoKategori: "CAT1", grupCode: "DOGALGAZ_YAKIT" },
  { birim: "İtfaiye DB", ad: "Jeneratör yakıt tüketimi", veriBirimi: "L dizel", isoKategori: "CAT1", grupCode: "JENERATOR" },
  { birim: "İtfaiye DB", ad: "Yangın söndürme köpüğü/kimyasalları", veriBirimi: "kg / L", isoKategori: "CAT4", grupCode: "SATIN_MALZEME" },
  { birim: "İtfaiye DB", ad: "Yangın söndürme gazları", veriBirimi: "kg gaz", isoKategori: "CAT1", grupCode: "SOGUTUCU_GAZ" },
  { birim: "İtfaiye DB", ad: "Tatbikat yakıt ve ekipman tüketimi", veriBirimi: "L / kg / adet", isoKategori: "CAT1", grupCode: "ARAC_YAKIT" },
  { birim: "İtfaiye DB", ad: "Kişisel koruyucu ekipman alımları", veriBirimi: "adet / kg", isoKategori: "CAT4", grupCode: "SATIN_MALZEME" },
  { birim: "İtfaiye DB", ad: "Hortum, ekipman, araç bakım malzemeleri", veriBirimi: "kg / adet / TL", isoKategori: "CAT4", grupCode: "ARAC_YAKIT" },
  { birim: "İtfaiye DB", ad: "Eğitim ve tatbikat atıkları", veriBirimi: "kg / ton", isoKategori: "CAT4", grupCode: "ATIK_BERTARAF" },
  { birim: "İtfaiye DB", ad: "Soğutucu sistem gaz kaçakları", veriBirimi: "kg gaz", isoKategori: "CAT1", grupCode: "SOGUTUCU_GAZ" },
  { birim: "İtfaiye DB", ad: "İtfaiye personeli iş seyahatleri", veriBirimi: "km / geceleme", isoKategori: "CAT3", grupCode: "PERSONEL_ULASIM" },
  { birim: "Kent Tarihi, Tanıtım ve Turizm DB", ad: "Tanıtım ofisleri elektrik tüketimi", veriBirimi: "kWh", isoKategori: "CAT2", grupCode: "ELEKTRIK" },
  { birim: "Kent Tarihi, Tanıtım ve Turizm DB", ad: "Tanıtım ofisleri doğalgaz tüketimi", veriBirimi: "m³", isoKategori: "CAT1", grupCode: "DOGALGAZ_YAKIT" },
  { birim: "Kent Tarihi, Tanıtım ve Turizm DB", ad: "Basılı tanıtım materyalleri", veriBirimi: "adet / kg kağıt", isoKategori: "CAT4", grupCode: "ETKINLIK_SOSYAL" },
  { birim: "Kent Tarihi, Tanıtım ve Turizm DB", ad: "Kültürel/turistik etkinlik ulaşımı", veriBirimi: "kişi-km / araç-km", isoKategori: "CAT3", grupCode: "TOPLU_TASIMA" },
  { birim: "Kent Tarihi, Tanıtım ve Turizm DB", ad: "Rehberli gezi ve saha etkinlik araçları yakıtı", veriBirimi: "L / km", isoKategori: "CAT3", grupCode: "ARAC_YAKIT" },
  { birim: "Kent Tarihi, Tanıtım ve Turizm DB", ad: "Organizasyon hizmetleri", veriBirimi: "TL", isoKategori: "CAT4", grupCode: "ETKINLIK_SOSYAL" },
  { birim: "Kent Tarihi, Tanıtım ve Turizm DB", ad: "Dijital tanıtım, web, medya hizmetleri", veriBirimi: "TL / kWh", isoKategori: "CAT4", grupCode: "BT_DIJITAL" },
  { birim: "Kent Tarihi, Tanıtım ve Turizm DB", ad: "Etkinlik atıkları", veriBirimi: "kg / ton", isoKategori: "CAT4", grupCode: "ATIK_BERTARAF" },
  { birim: "Kent Tarihi, Tanıtım ve Turizm DB", ad: "Sergi, stant, fuar malzemeleri", veriBirimi: "kg / adet", isoKategori: "CAT4", grupCode: "SATIN_MALZEME" },
  { birim: "Kent Tarihi, Tanıtım ve Turizm DB", ad: "Tanıtım amaçlı hediye/promosyon ürünleri", veriBirimi: "adet / kg", isoKategori: "CAT4", grupCode: "ETKINLIK_SOSYAL" },
  { birim: "Kültür, Sanat ve Sosyal İşler DB", ad: "Kültür merkezleri elektrik tüketimi", veriBirimi: "kWh", isoKategori: "CAT2", grupCode: "ELEKTRIK" },
  { birim: "Kültür, Sanat ve Sosyal İşler DB", ad: "Kültür merkezleri doğalgaz tüketimi", veriBirimi: "m³", isoKategori: "CAT1", grupCode: "DOGALGAZ_YAKIT" },
  { birim: "Kültür, Sanat ve Sosyal İşler DB", ad: "Sahne ışık ve ses sistemleri elektrik tüketimi", veriBirimi: "kWh", isoKategori: "CAT2", grupCode: "ELEKTRIK" },
  { birim: "Kültür, Sanat ve Sosyal İşler DB", ad: "Etkinlik jeneratör yakıt tüketimi", veriBirimi: "L dizel", isoKategori: "CAT1", grupCode: "JENERATOR" },
  { birim: "Kültür, Sanat ve Sosyal İşler DB", ad: "Sanat etkinlikleri ulaşım verileri", veriBirimi: "kişi-km / araç-km", isoKategori: "CAT3", grupCode: "TOPLU_TASIMA" },
  { birim: "Kültür, Sanat ve Sosyal İşler DB", ad: "Sanatçı/ekip konaklamaları", veriBirimi: "geceleme", isoKategori: "CAT3", grupCode: "PERSONEL_ULASIM" },
  { birim: "Kültür, Sanat ve Sosyal İşler DB", ad: "Etkinlik sahne, dekor, stant malzemeleri", veriBirimi: "kg / adet / TL", isoKategori: "CAT4", grupCode: "ETKINLIK_SOSYAL" },
  { birim: "Kültür, Sanat ve Sosyal İşler DB", ad: "Basılı afiş, broşür, bilet, katalog", veriBirimi: "adet / kg", isoKategori: "CAT4", grupCode: "ETKINLIK_SOSYAL" },
  { birim: "Kültür, Sanat ve Sosyal İşler DB", ad: "Etkinlik atıkları", veriBirimi: "kg / ton", isoKategori: "CAT4", grupCode: "ATIK_BERTARAF" },
  { birim: "Kültür, Sanat ve Sosyal İşler DB", ad: "İkram ve yemek hizmetleri", veriBirimi: "adet / TL", isoKategori: "CAT4", grupCode: "ETKINLIK_SOSYAL" },
  { birim: "Kültür, Sanat ve Sosyal İşler DB", ad: "Kiralık ekipman ve teknik hizmetler", veriBirimi: "TL", isoKategori: "CAT4", grupCode: "SATIN_HIZMET" },
  { birim: "Mali Hizmetler DB", ad: "Ofis elektrik tüketimi", veriBirimi: "kWh", isoKategori: "CAT2", grupCode: "ELEKTRIK" },
  { birim: "Mali Hizmetler DB", ad: "Ofis doğalgaz tüketimi", veriBirimi: "m³", isoKategori: "CAT1", grupCode: "DOGALGAZ_YAKIT" },
  { birim: "Mali Hizmetler DB", ad: "Evrak, dosya, kağıt tüketimi", veriBirimi: "kg / adet", isoKategori: "CAT4", grupCode: "SATIN_MALZEME" },
  { birim: "Mali Hizmetler DB", ad: "Yazıcı ve toner tüketimi", veriBirimi: "adet / kg", isoKategori: "CAT4", grupCode: "SATIN_MALZEME" },
  { birim: "Mali Hizmetler DB", ad: "Dijital arşiv ve veri işleme hizmetleri", veriBirimi: "TL / kWh", isoKategori: "CAT4", grupCode: "BT_DIJITAL" },
  { birim: "Mali Hizmetler DB", ad: "Mali denetim ve danışmanlık hizmetleri", veriBirimi: "TL", isoKategori: "CAT4", grupCode: "SATIN_HIZMET" },
  { birim: "Mali Hizmetler DB", ad: "Personel ulaşımı", veriBirimi: "kişi-km", isoKategori: "CAT3", grupCode: "PERSONEL_ULASIM" },
  { birim: "Mali Hizmetler DB", ad: "Toplantı ve çalıştay organizasyonları", veriBirimi: "adet / kişi", isoKategori: "CAT3_4", grupCode: "ETKINLIK_SOSYAL" },
  { birim: "Mali Hizmetler DB", ad: "Ofis ekipmanı alımları", veriBirimi: "adet", isoKategori: "CAT4", grupCode: "SATIN_MALZEME" },
  { birim: "Mali Hizmetler DB", ad: "Ofis atıkları", veriBirimi: "kg / ton", isoKategori: "CAT4", grupCode: "ATIK_BERTARAF" },
  { birim: "Mezarlıklar Daire Başkanlığı", ad: "Cenaze hizmet araçları yakıt tüketimi", veriBirimi: "L", isoKategori: "CAT1", grupCode: "ARAC_YAKIT" },
  { birim: "Mezarlıklar Daire Başkanlığı", ad: "Mezarlık tesisleri elektrik tüketimi", veriBirimi: "kWh", isoKategori: "CAT2", grupCode: "ELEKTRIK" },
  { birim: "Mezarlıklar Daire Başkanlığı", ad: "Mezarlık tesisleri doğalgaz tüketimi", veriBirimi: "m³", isoKategori: "CAT1", grupCode: "DOGALGAZ_YAKIT" },
  { birim: "Mezarlıklar Daire Başkanlığı", ad: "Morg ve soğutma sistemleri elektrik tüketimi", veriBirimi: "kWh", isoKategori: "CAT2", grupCode: "ELEKTRIK" },
  { birim: "Mezarlıklar Daire Başkanlığı", ad: "Morg/soğutucu gaz kaçakları", veriBirimi: "kg gaz", isoKategori: "CAT1", grupCode: "SOGUTUCU_GAZ" },
  { birim: "Mezarlıklar Daire Başkanlığı", ad: "Mezarlık bakım araçları yakıt tüketimi", veriBirimi: "L", isoKategori: "CAT1", grupCode: "ARAC_YAKIT" },
  { birim: "Mezarlıklar Daire Başkanlığı", ad: "Çim biçme, budama, peyzaj ekipmanları yakıtı", veriBirimi: "L", isoKategori: "CAT1", grupCode: "ARAC_YAKIT" },
  { birim: "Mezarlıklar Daire Başkanlığı", ad: "Sulama pompaları elektrik tüketimi", veriBirimi: "kWh", isoKategori: "CAT2", grupCode: "ELEKTRIK" },
  { birim: "Mezarlıklar Daire Başkanlığı", ad: "Peyzaj malzemeleri, toprak, gübre, bitki alımları", veriBirimi: "kg / ton / adet", isoKategori: "CAT4", grupCode: "PARK_TARIM" },
  { birim: "Mezarlıklar Daire Başkanlığı", ad: "Budama ve yeşil atıklar", veriBirimi: "kg / ton", isoKategori: "CAT4", grupCode: "ATIK_BERTARAF" },
  { birim: "Mezarlıklar Daire Başkanlığı", ad: "Mezarlık hizmetlerinde kullanılan sarf malzemeleri", veriBirimi: "adet / kg", isoKategori: "CAT4", grupCode: "SATIN_HIZMET" },
  { birim: "Muhtarlık İşleri DB", ad: "Muhtarlık koordinasyon toplantıları ulaşım verileri", veriBirimi: "km / kişi-km", isoKategori: "CAT3", grupCode: "PERSONEL_ULASIM" },
  { birim: "Muhtarlık İşleri DB", ad: "Saha ziyaret araçları yakıt tüketimi", veriBirimi: "L / km", isoKategori: "CAT3", grupCode: "ARAC_YAKIT" },
  { birim: "Muhtarlık İşleri DB", ad: "Ofis destek malzemeleri", veriBirimi: "kg / adet / TL", isoKategori: "CAT4", grupCode: "SATIN_HIZMET" },
  { birim: "Muhtarlık İşleri DB", ad: "Evrak, kağıt, dosya tüketimi", veriBirimi: "kg / adet", isoKategori: "CAT4", grupCode: "SATIN_MALZEME" },
  { birim: "Muhtarlık İşleri DB", ad: "Toplantı organizasyonları", veriBirimi: "kişi / adet / TL", isoKategori: "CAT3_4", grupCode: "ETKINLIK_SOSYAL" },
  { birim: "Muhtarlık İşleri DB", ad: "Dijital iletişim ve yazılım hizmetleri", veriBirimi: "TL", isoKategori: "CAT4", grupCode: "BT_DIJITAL" },
  { birim: "Muhtarlık İşleri DB", ad: "Muhtarlık hizmet alanları elektrik tüketimi varsa", veriBirimi: "kWh", isoKategori: "CAT2", grupCode: "ELEKTRIK" },
  { birim: "Muhtarlık İşleri DB", ad: "Ofis atıkları", veriBirimi: "kg / ton", isoKategori: "CAT4", grupCode: "ATIK_BERTARAF" },
  { birim: "Park Bahçe ve Yeşil Alanlar DB", ad: "Park aydınlatmaları elektrik tüketimi", veriBirimi: "kWh", isoKategori: "CAT2", grupCode: "ELEKTRIK" },
  { birim: "Park Bahçe ve Yeşil Alanlar DB", ad: "Sulama pompaları elektrik tüketimi", veriBirimi: "kWh", isoKategori: "CAT2", grupCode: "ELEKTRIK" },
  { birim: "Park Bahçe ve Yeşil Alanlar DB", ad: "Sulama araçları yakıt tüketimi", veriBirimi: "L", isoKategori: "CAT1", grupCode: "ARAC_YAKIT" },
  { birim: "Park Bahçe ve Yeşil Alanlar DB", ad: "Park bakım araçları yakıt tüketimi", veriBirimi: "L", isoKategori: "CAT1", grupCode: "ARAC_YAKIT" },
  { birim: "Park Bahçe ve Yeşil Alanlar DB", ad: "Çim biçme makineleri yakıt tüketimi", veriBirimi: "L benzin / dizel", isoKategori: "CAT1", grupCode: "ARAC_YAKIT" },
  { birim: "Park Bahçe ve Yeşil Alanlar DB", ad: "Budama ve saha ekipmanları yakıt tüketimi", veriBirimi: "L", isoKategori: "CAT1", grupCode: "ARAC_YAKIT" },
  { birim: "Park Bahçe ve Yeşil Alanlar DB", ad: "Gübre kullanımı", veriBirimi: "kg", isoKategori: "CAT4", grupCode: "PARK_TARIM" },
  { birim: "Park Bahçe ve Yeşil Alanlar DB", ad: "Toprak, torf, kum, peyzaj malzemesi alımı", veriBirimi: "kg / ton", isoKategori: "CAT4", grupCode: "PARK_TARIM" },
  { birim: "Park Bahçe ve Yeşil Alanlar DB", ad: "Fidan, fide, bitki alımları", veriBirimi: "adet / kg", isoKategori: "CAT4", grupCode: "PARK_TARIM" },
  { birim: "Park Bahçe ve Yeşil Alanlar DB", ad: "Park mobilyaları, bank, oyun grubu, spor ekipmanı", veriBirimi: "adet / kg", isoKategori: "CAT4", grupCode: "PARK_TARIM" },
  { birim: "Park Bahçe ve Yeşil Alanlar DB", ad: "Budama atıkları", veriBirimi: "kg / ton", isoKategori: "CAT4", grupCode: "ATIK_BERTARAF" },
  { birim: "Park Bahçe ve Yeşil Alanlar DB", ad: "Yeşil atık kompost süreci", veriBirimi: "ton", isoKategori: "CAT4", grupCode: "ATIK_BERTARAF" },
  { birim: "Park Bahçe ve Yeşil Alanlar DB", ad: "Sulama suyu tüketimi", veriBirimi: "m³", isoKategori: "CAT4", grupCode: "DOGALGAZ_YAKIT" },
  { birim: "Park Bahçe ve Yeşil Alanlar DB", ad: "Sera veya fidanlık elektrik/doğalgaz tüketimi", veriBirimi: "kWh / m³", isoKategori: "CAT1_2", grupCode: "ELEKTRIK" },
  { birim: "Raylı Sistem DB", ad: "Raylı sistem işletme elektrik tüketimi", veriBirimi: "kWh", isoKategori: "CAT2", grupCode: "TOPLU_TASIMA" },
  { birim: "Raylı Sistem DB", ad: "İstasyon elektrik tüketimi", veriBirimi: "kWh", isoKategori: "CAT2", grupCode: "ELEKTRIK" },
  { birim: "Raylı Sistem DB", ad: "Yürüyen merdiven/asansör elektrik tüketimi", veriBirimi: "kWh", isoKategori: "CAT2", grupCode: "ELEKTRIK" },
  { birim: "Raylı Sistem DB", ad: "Havalandırma ve iklimlendirme elektrik tüketimi", veriBirimi: "kWh", isoKategori: "CAT2", grupCode: "ELEKTRIK" },
  { birim: "Raylı Sistem DB", ad: "Raylı sistem inşaatlarında beton kullanımı", veriBirimi: "m³ / ton", isoKategori: "CAT4", grupCode: "TOPLU_TASIMA" },
  { birim: "Raylı Sistem DB", ad: "Çelik/ray kullanımı", veriBirimi: "ton", isoKategori: "CAT4", grupCode: "INSAAT_YOL" },
  { birim: "Raylı Sistem DB", ad: "Kablo, ekipman, sinyalizasyon malzemeleri", veriBirimi: "kg / adet / TL", isoKategori: "CAT4", grupCode: "SATIN_HIZMET" },
  { birim: "Raylı Sistem DB", ad: "Kazı ve hafriyat miktarı", veriBirimi: "m³ / ton", isoKategori: "CAT4", grupCode: "INSAAT_YOL" },
  { birim: "Raylı Sistem DB", ad: "Hafriyat taşıma mesafesi", veriBirimi: "ton-km", isoKategori: "CAT3", grupCode: "INSAAT_YOL" },
  { birim: "Raylı Sistem DB", ad: "Saha kontrol araçları yakıt tüketimi", veriBirimi: "L / km", isoKategori: "CAT3", grupCode: "ARAC_YAKIT" },
  { birim: "Raylı Sistem DB", ad: "Bakım ve modernizasyon malzemeleri", veriBirimi: "kg / adet / TL", isoKategori: "CAT4", grupCode: "SATIN_HIZMET" },
  { birim: "Raylı Sistem DB", ad: "Raylı sistem projeleri danışmanlık hizmetleri", veriBirimi: "TL", isoKategori: "CAT4", grupCode: "TOPLU_TASIMA" },
  { birim: "Raylı Sistem DB", ad: "İnşaat ekipmanları yakıt tüketimi", veriBirimi: "L", isoKategori: "CAT1", grupCode: "ARAC_YAKIT" },
  { birim: "Raylı Sistem DB", ad: "İstasyon atıkları", veriBirimi: "kg / ton", isoKategori: "CAT4", grupCode: "ATIK_BERTARAF" },
  { birim: "Sağlık DB", ad: "Sağlık tesisleri elektrik tüketimi", veriBirimi: "kWh", isoKategori: "CAT2", grupCode: "ELEKTRIK" },
  { birim: "Sağlık DB", ad: "Sağlık tesisleri doğalgaz tüketimi", veriBirimi: "m³", isoKategori: "CAT1", grupCode: "DOGALGAZ_YAKIT" },
  { birim: "Sağlık DB", ad: "Ambulans veya sağlık hizmet araçları yakıt tüketimi", veriBirimi: "L", isoKategori: "CAT1", grupCode: "ARAC_YAKIT" },
  { birim: "Sağlık DB", ad: "Mobil sağlık hizmet araçları yakıt tüketimi", veriBirimi: "L", isoKategori: "CAT1", grupCode: "ARAC_YAKIT" },
  { birim: "Sağlık DB", ad: "Tıbbi sarf malzemeleri", veriBirimi: "kg / adet / TL", isoKategori: "CAT4", grupCode: "ATIK_BERTARAF" },
  { birim: "Sağlık DB", ad: "Tıbbi atıklar", veriBirimi: "kg / ton", isoKategori: "CAT4", grupCode: "ATIK_BERTARAF" },
  { birim: "Sağlık DB", ad: "İlaç ve medikal ürün atıkları", veriBirimi: "kg", isoKategori: "CAT4", grupCode: "ATIK_BERTARAF" },
  { birim: "Sağlık DB", ad: "Soğuk zincir buzdolabı/cihaz elektrik tüketimi", veriBirimi: "kWh", isoKategori: "CAT2", grupCode: "ELEKTRIK" },
  { birim: "Sağlık DB", ad: "Soğutucu gaz kaçakları", veriBirimi: "kg gaz", isoKategori: "CAT1", grupCode: "SOGUTUCU_GAZ" },
  { birim: "Sağlık DB", ad: "Laboratuvar hizmetleri", veriBirimi: "TL / numune", isoKategori: "CAT4", grupCode: "SATIN_HIZMET" },
  { birim: "Sağlık DB", ad: "Sağlık tarama organizasyonları ulaşım verileri", veriBirimi: "km / kişi-km", isoKategori: "CAT3", grupCode: "PERSONEL_ULASIM" },
  { birim: "Sağlık DB", ad: "Temizlik ve dezenfeksiyon kimyasalları", veriBirimi: "kg / L", isoKategori: "CAT4", grupCode: "SATIN_HIZMET" },
  { birim: "Satınalma DB", ad: "Mal alımları", veriBirimi: "kg / ton / adet / TL", isoKategori: "CAT4", grupCode: "SATIN_HIZMET" },
  { birim: "Satınalma DB", ad: "Hizmet alımları", veriBirimi: "TL / fiziksel veri", isoKategori: "CAT4", grupCode: "SATIN_HIZMET" },
  { birim: "Satınalma DB", ad: "Sermaye varlığı alımları", veriBirimi: "adet / TL", isoKategori: "CAT4", grupCode: "SATIN_HIZMET" },
  { birim: "Satınalma DB", ad: "Araç, makine, ekipman alımları", veriBirimi: "adet / kg / TL", isoKategori: "CAT4", grupCode: "ARAC_YAKIT" },
  { birim: "Satınalma DB", ad: "Bilgisayar ve elektronik cihaz alımları", veriBirimi: "adet", isoKategori: "CAT4", grupCode: "BT_DIJITAL" },
  { birim: "Satınalma DB", ad: "Ofis mobilyası alımları", veriBirimi: "adet / kg", isoKategori: "CAT4", grupCode: "SATIN_MALZEME" },
  { birim: "Satınalma DB", ad: "Kağıt, toner, kırtasiye alımları", veriBirimi: "kg / adet", isoKategori: "CAT4", grupCode: "SATIN_MALZEME" },
  { birim: "Satınalma DB", ad: "Temizlik malzemeleri alımları", veriBirimi: "kg / L", isoKategori: "CAT4", grupCode: "SATIN_HIZMET" },
  { birim: "Satınalma DB", ad: "İnşaat malzemesi alımları", veriBirimi: "ton / m³", isoKategori: "CAT4", grupCode: "DOGALGAZ_YAKIT" },
  { birim: "Satınalma DB", ad: "Asfalt, beton, çimento, çelik alımları", veriBirimi: "ton / m³", isoKategori: "CAT4", grupCode: "INSAAT_YOL" },
  { birim: "Satınalma DB", ad: "Yemek, güvenlik, temizlik hizmetleri", veriBirimi: "TL / fiziksel veri", isoKategori: "CAT4", grupCode: "ETKINLIK_SOSYAL" },
  { birim: "Satınalma DB", ad: "Bakım-onarım hizmetleri", veriBirimi: "TL / parça miktarı", isoKategori: "CAT4", grupCode: "SATIN_HIZMET" },
  { birim: "Satınalma DB", ad: "Tedarikçi bazlı ürün karbon ayak izi verileri", veriBirimi: "kgCO₂e/birim", isoKategori: "CAT4", grupCode: "SATIN_MALZEME" },
  { birim: "Sosyal Hizmetler DB", ad: "Sosyal yardım dağıtım araçları yakıt tüketimi", veriBirimi: "L", isoKategori: "CAT1", grupCode: "ARAC_YAKIT" },
  { birim: "Sosyal Hizmetler DB", ad: "Gıda yardımı ve yardım kolisi içerikleri", veriBirimi: "kg / adet", isoKategori: "CAT4", grupCode: "SATIN_MALZEME" },
  { birim: "Sosyal Hizmetler DB", ad: "Yardım kolisi ambalajları", veriBirimi: "kg karton/plastik", isoKategori: "CAT4", grupCode: "SATIN_MALZEME" },
  { birim: "Sosyal Hizmetler DB", ad: "Sosyal tesisler elektrik tüketimi", veriBirimi: "kWh", isoKategori: "CAT2", grupCode: "ELEKTRIK" },
  { birim: "Sosyal Hizmetler DB", ad: "Sosyal tesisler doğalgaz tüketimi", veriBirimi: "m³", isoKategori: "CAT1", grupCode: "DOGALGAZ_YAKIT" },
  { birim: "Sosyal Hizmetler DB", ad: "Yemek/öğün hizmetleri", veriBirimi: "adet öğün", isoKategori: "CAT4", grupCode: "ETKINLIK_SOSYAL" },
  { birim: "Sosyal Hizmetler DB", ad: "Depolama alanları elektrik tüketimi", veriBirimi: "kWh", isoKategori: "CAT2", grupCode: "ATIK_BERTARAF" },
  { birim: "Sosyal Hizmetler DB", ad: "Lojistik ve dağıtım hizmetleri", veriBirimi: "km / ton-km", isoKategori: "CAT3", grupCode: "PERSONEL_ULASIM" },
  { birim: "Sosyal Hizmetler DB", ad: "Sosyal yardım organizasyonları atıkları", veriBirimi: "kg / ton", isoKategori: "CAT4", grupCode: "ATIK_BERTARAF" },
  { birim: "Sosyal Hizmetler DB", ad: "Tekstil, hijyen, kırtasiye yardımları", veriBirimi: "kg / adet / TL", isoKategori: "CAT4", grupCode: "SATIN_HIZMET" },
  { birim: "Sosyal Hizmetler DB", ad: "Saha personeli ulaşımı", veriBirimi: "km", isoKategori: "CAT3", grupCode: "PERSONEL_ULASIM" },
  { birim: "Strateji Geliştirme DB", ad: "Ofis elektrik tüketimi", veriBirimi: "kWh", isoKategori: "CAT2", grupCode: "ELEKTRIK" },
  { birim: "Strateji Geliştirme DB", ad: "Ofis doğalgaz tüketimi", veriBirimi: "m³", isoKategori: "CAT1", grupCode: "DOGALGAZ_YAKIT" },
  { birim: "Strateji Geliştirme DB", ad: "Danışmanlık hizmetleri", veriBirimi: "TL", isoKategori: "CAT4", grupCode: "SATIN_HIZMET" },
  { birim: "Strateji Geliştirme DB", ad: "Veri toplama, analiz ve raporlama hizmetleri", veriBirimi: "TL", isoKategori: "CAT4", grupCode: "SATIN_HIZMET" },
  { birim: "Strateji Geliştirme DB", ad: "Kurumsal rapor baskıları", veriBirimi: "adet / kg kağıt", isoKategori: "CAT4", grupCode: "SATIN_MALZEME" },
  { birim: "Strateji Geliştirme DB", ad: "Çalıştay ve toplantı organizasyonları", veriBirimi: "kişi / adet / TL", isoKategori: "CAT3_4", grupCode: "ETKINLIK_SOSYAL" },
  { birim: "Strateji Geliştirme DB", ad: "İş seyahatleri", veriBirimi: "km / yolcu-km / geceleme", isoKategori: "CAT3", grupCode: "TOPLU_TASIMA" },
  { birim: "Strateji Geliştirme DB", ad: "Dijital raporlama platformları ve yazılım hizmetleri", veriBirimi: "TL", isoKategori: "CAT4", grupCode: "BT_DIJITAL" },
  { birim: "Strateji Geliştirme DB", ad: "Ofis sarf malzemeleri", veriBirimi: "kg / adet", isoKategori: "CAT4", grupCode: "SATIN_MALZEME" },
  { birim: "Strateji Geliştirme DB", ad: "Ofis atıkları", veriBirimi: "kg / ton", isoKategori: "CAT4", grupCode: "ATIK_BERTARAF" },
  { birim: "Tarımsal Hizmetler DB", ad: "Fide/fidan alımları", veriBirimi: "adet / kg", isoKategori: "CAT4", grupCode: "PARK_TARIM" },
  { birim: "Tarımsal Hizmetler DB", ad: "Gübre kullanımı", veriBirimi: "kg", isoKategori: "CAT4", grupCode: "PARK_TARIM" },
  { birim: "Tarımsal Hizmetler DB", ad: "Pestisit / zirai ilaç kullanımı", veriBirimi: "kg / L", isoKategori: "CAT4", grupCode: "OFIS_IDARI" },
  { birim: "Tarımsal Hizmetler DB", ad: "Tarım ekipmanları yakıt tüketimi", veriBirimi: "L", isoKategori: "CAT1", grupCode: "ARAC_YAKIT" },
  { birim: "Tarımsal Hizmetler DB", ad: "Traktör ve iş makineleri yakıt tüketimi", veriBirimi: "L", isoKategori: "CAT1", grupCode: "ARAC_YAKIT" },
  { birim: "Tarımsal Hizmetler DB", ad: "Sulama pompaları elektrik tüketimi", veriBirimi: "kWh", isoKategori: "CAT2", grupCode: "ELEKTRIK" },
  { birim: "Tarımsal Hizmetler DB", ad: "Sera elektrik tüketimi", veriBirimi: "kWh", isoKategori: "CAT2", grupCode: "ELEKTRIK" },
  { birim: "Tarımsal Hizmetler DB", ad: "Sera doğalgaz/ısıtma tüketimi", veriBirimi: "m³ / kWh", isoKategori: "CAT1_2", grupCode: "ELEKTRIK" },
  { birim: "Tarımsal Hizmetler DB", ad: "Tarımsal atıklar", veriBirimi: "kg / ton", isoKategori: "CAT4", grupCode: "ATIK_BERTARAF" },
  { birim: "Tarımsal Hizmetler DB", ad: "Toprak, torf, kompost kullanımı", veriBirimi: "kg / ton", isoKategori: "CAT4", grupCode: "ATIK_BERTARAF" },
  { birim: "Tarımsal Hizmetler DB", ad: "Tarımsal eğitim ve saha ulaşımı", veriBirimi: "km", isoKategori: "CAT3", grupCode: "PERSONEL_ULASIM" },
  { birim: "Tarımsal Hizmetler DB", ad: "Soğuk hava/depolama elektrik tüketimi varsa", veriBirimi: "kWh", isoKategori: "CAT2", grupCode: "ATIK_BERTARAF" },
  { birim: "Ulaşım DB", ad: "Belediye ulaşım araçları yakıt tüketimi", veriBirimi: "L", isoKategori: "CAT1", grupCode: "ARAC_YAKIT" },
  { birim: "Ulaşım DB", ad: "Toplu taşıma araçları yakıt tüketimi", veriBirimi: "L dizel / CNG / benzin", isoKategori: "CAT1", grupCode: "TOPLU_TASIMA" },
  { birim: "Ulaşım DB", ad: "Elektrikli toplu taşıma elektrik tüketimi", veriBirimi: "kWh", isoKategori: "CAT2", grupCode: "TOPLU_TASIMA" },
  { birim: "Ulaşım DB", ad: "Otobüs araç-km verisi", veriBirimi: "araç-km", isoKategori: "KENT", grupCode: "TOPLU_TASIMA" },
  { birim: "Ulaşım DB", ad: "Yolcu-km verisi", veriBirimi: "yolcu-km", isoKategori: "KENT", grupCode: "TOPLU_TASIMA" },
  { birim: "Ulaşım DB", ad: "Servis taşımacılığı verileri", veriBirimi: "araç-km / yolcu-km", isoKategori: "CAT3", grupCode: "TOPLU_TASIMA" },
  { birim: "Ulaşım DB", ad: "Minibüs/dolmuş verileri", veriBirimi: "araç-km / yakıt", isoKategori: "KENT", grupCode: "TOPLU_TASIMA" },
  { birim: "Ulaşım DB", ad: "Taksi verileri", veriBirimi: "araç-km / yakıt", isoKategori: "KENT", grupCode: "TOPLU_TASIMA" },
  { birim: "Ulaşım DB", ad: "Ağır tonaj taşıma izinleri", veriBirimi: "ton-km", isoKategori: "CAT3", grupCode: "PERSONEL_ULASIM" },
  { birim: "Ulaşım DB", ad: "Hafriyat taşıma güzergahları", veriBirimi: "ton-km", isoKategori: "CAT3", grupCode: "INSAAT_YOL" },
  { birim: "Ulaşım DB", ad: "Deniz yük taşımacılığı", veriBirimi: "ton-km / yakıt", isoKategori: "CAT3", grupCode: "ARAC_YAKIT" },
  { birim: "Ulaşım DB", ad: "Terminal elektrik tüketimi", veriBirimi: "kWh", isoKategori: "CAT2", grupCode: "TOPLU_TASIMA" },
  { birim: "Ulaşım DB", ad: "Terminal doğalgaz tüketimi", veriBirimi: "m³", isoKategori: "CAT1", grupCode: "TOPLU_TASIMA" },
  { birim: "Ulaşım DB", ad: "Terminal bakım-onarım malzemeleri", veriBirimi: "kg / TL", isoKategori: "CAT4", grupCode: "TOPLU_TASIMA" },
  { birim: "Ulaşım DB", ad: "Trafik sinyalizasyon sistemleri elektrik tüketimi", veriBirimi: "kWh", isoKategori: "CAT2", grupCode: "ELEKTRIK" },
  { birim: "Ulaşım DB", ad: "Akıllı ulaşım sistemleri elektrik tüketimi", veriBirimi: "kWh", isoKategori: "CAT2", grupCode: "ELEKTRIK" },
  { birim: "Ulaşım DB", ad: "Ulaşım planlama danışmanlık hizmetleri", veriBirimi: "TL", isoKategori: "CAT4", grupCode: "PERSONEL_ULASIM" },
  { birim: "Yazı İşleri ve Kararlar DB", ad: "Ofis elektrik tüketimi", veriBirimi: "kWh", isoKategori: "CAT2", grupCode: "ELEKTRIK" },
  { birim: "Yazı İşleri ve Kararlar DB", ad: "Ofis doğalgaz tüketimi", veriBirimi: "m³", isoKategori: "CAT1", grupCode: "DOGALGAZ_YAKIT" },
  { birim: "Yazı İşleri ve Kararlar DB", ad: "Evrak, dosya ve karar dokümanları kağıt tüketimi", veriBirimi: "kg / adet", isoKategori: "CAT4", grupCode: "SATIN_MALZEME" },
  { birim: "Yazı İşleri ve Kararlar DB", ad: "Basılı meclis/komisyon evrakları", veriBirimi: "adet / kg", isoKategori: "CAT4", grupCode: "OFIS_IDARI" },
  { birim: "Yazı İşleri ve Kararlar DB", ad: "Dijital arşiv sistemleri hizmetleri", veriBirimi: "TL / kWh", isoKategori: "CAT4", grupCode: "BT_DIJITAL" },
  { birim: "Yazı İşleri ve Kararlar DB", ad: "Toplantı salonu elektrik tüketimi", veriBirimi: "kWh", isoKategori: "CAT2", grupCode: "ELEKTRIK" },
  { birim: "Yazı İşleri ve Kararlar DB", ad: "Kurul/toplantı organizasyonları", veriBirimi: "kişi / adet", isoKategori: "CAT3_4", grupCode: "ETKINLIK_SOSYAL" },
  { birim: "Yazı İşleri ve Kararlar DB", ad: "Yazıcı, toner, ofis ekipmanı tüketimi", veriBirimi: "adet", isoKategori: "CAT4", grupCode: "SATIN_MALZEME" },
  { birim: "Yazı İşleri ve Kararlar DB", ad: "Evrak dağıtım/kargo hizmetleri", veriBirimi: "km / TL", isoKategori: "CAT3_4", grupCode: "PERSONEL_ULASIM" },
  { birim: "Yazı İşleri ve Kararlar DB", ad: "Ofis atıkları", veriBirimi: "kg / ton", isoKategori: "CAT4", grupCode: "ATIK_BERTARAF" },
  { birim: "Yol Bakım ve Altyapı Koordinasyon DB", ad: "Asfalt kullanımı", veriBirimi: "ton", isoKategori: "CAT4", grupCode: "INSAAT_YOL" },
  { birim: "Yol Bakım ve Altyapı Koordinasyon DB", ad: "Beton kullanımı", veriBirimi: "m³ / ton", isoKategori: "CAT4", grupCode: "INSAAT_YOL" },
  { birim: "Yol Bakım ve Altyapı Koordinasyon DB", ad: "Çimento kullanımı", veriBirimi: "ton", isoKategori: "CAT4", grupCode: "INSAAT_YOL" },
  { birim: "Yol Bakım ve Altyapı Koordinasyon DB", ad: "Agrega, kum, çakıl kullanımı", veriBirimi: "ton", isoKategori: "CAT4", grupCode: "INSAAT_YOL" },
  { birim: "Yol Bakım ve Altyapı Koordinasyon DB", ad: "Bordür, parke taşı, altyapı elemanları", veriBirimi: "adet / ton", isoKategori: "CAT4", grupCode: "INSAAT_YOL" },
  { birim: "Yol Bakım ve Altyapı Koordinasyon DB", ad: "İş makineleri yakıt tüketimi", veriBirimi: "L dizel", isoKategori: "CAT1", grupCode: "ARAC_YAKIT" },
  { birim: "Yol Bakım ve Altyapı Koordinasyon DB", ad: "Yol bakım araçları yakıt tüketimi", veriBirimi: "L", isoKategori: "CAT1", grupCode: "INSAAT_YOL" },
  { birim: "Yol Bakım ve Altyapı Koordinasyon DB", ad: "Kazı miktarı", veriBirimi: "m³", isoKategori: "CAT4", grupCode: "INSAAT_YOL" },
  { birim: "Yol Bakım ve Altyapı Koordinasyon DB", ad: "Hafriyat miktarı", veriBirimi: "ton / m³", isoKategori: "CAT4", grupCode: "INSAAT_YOL" },
  { birim: "Yol Bakım ve Altyapı Koordinasyon DB", ad: "Hafriyat taşıma mesafesi", veriBirimi: "ton-km", isoKategori: "CAT3", grupCode: "INSAAT_YOL" },
  { birim: "Yol Bakım ve Altyapı Koordinasyon DB", ad: "İnşaat ve yıkıntı atıkları", veriBirimi: "ton", isoKategori: "CAT4", grupCode: "INSAAT_YOL" },
  { birim: "Yol Bakım ve Altyapı Koordinasyon DB", ad: "Yol çizgi boyası ve kimyasal kullanımı", veriBirimi: "kg / L", isoKategori: "CAT4", grupCode: "SATIN_MALZEME" },
  { birim: "Yol Bakım ve Altyapı Koordinasyon DB", ad: "Yol bakım şantiyeleri elektrik tüketimi", veriBirimi: "kWh", isoKategori: "CAT2", grupCode: "INSAAT_YOL" },
  { birim: "Yol Bakım ve Altyapı Koordinasyon DB", ad: "Şantiye jeneratör yakıtı", veriBirimi: "L", isoKategori: "CAT1", grupCode: "INSAAT_YOL" },
  { birim: "Yol Bakım ve Altyapı Koordinasyon DB", ad: "Bakım-onarım hizmet alımları", veriBirimi: "TL / malzeme miktarı", isoKategori: "CAT4", grupCode: "SATIN_HIZMET" },
  { birim: "Yol Bakım ve Altyapı Koordinasyon DB", ad: "Altyapı kazı ruhsatı süreçlerinden doğan saha kontrolleri", veriBirimi: "km", isoKategori: "CAT3", grupCode: "INSAAT_YOL" },
  { birim: "Zabıta Daire Başkanlığı", ad: "Zabıta araçları yakıt tüketimi", veriBirimi: "L", isoKategori: "CAT1", grupCode: "ARAC_YAKIT" },
  { birim: "Zabıta Daire Başkanlığı", ad: "Saha denetim ulaşımı", veriBirimi: "km / L yakıt", isoKategori: "CAT1", grupCode: "ARAC_YAKIT" },
  { birim: "Zabıta Daire Başkanlığı", ad: "Zabıta hizmet binaları elektrik tüketimi", veriBirimi: "kWh", isoKategori: "CAT2", grupCode: "ELEKTRIK" },
  { birim: "Zabıta Daire Başkanlığı", ad: "Zabıta hizmet binaları doğalgaz tüketimi", veriBirimi: "m³", isoKategori: "CAT1", grupCode: "DOGALGAZ_YAKIT" },
  { birim: "Zabıta Daire Başkanlığı", ad: "Telsiz, kamera, mobil cihaz enerji tüketimi", veriBirimi: "kWh / adet", isoKategori: "CAT2", grupCode: "ELEKTRIK" },
  { birim: "Zabıta Daire Başkanlığı", ad: "Üniforma ve kişisel ekipman alımları", veriBirimi: "adet / kg", isoKategori: "CAT4", grupCode: "SATIN_MALZEME" },
  { birim: "Zabıta Daire Başkanlığı", ad: "Denetim faaliyetlerinde kullanılan basılı evraklar", veriBirimi: "kg / adet", isoKategori: "CAT4", grupCode: "SATIN_HIZMET" },
  { birim: "Zabıta Daire Başkanlığı", ad: "Denetim sonucu oluşan atık/bertaraf kalemleri varsa", veriBirimi: "kg / ton", isoKategori: "CAT4", grupCode: "ATIK_BERTARAF" },
  { birim: "Zabıta Daire Başkanlığı", ad: "Eğitim ve toplantı faaliyetleri", veriBirimi: "kişi-km / materyal", isoKategori: "CAT3_4", grupCode: "PERSONEL_ULASIM" },
  { birim: "Zabıta Daire Başkanlığı", ad: "Araç bakım-onarım malzemeleri", veriBirimi: "kg / adet / TL", isoKategori: "CAT4", grupCode: "ARAC_YAKIT" },
  { birim: "Zabıta Daire Başkanlığı", ad: "Ofis atıkları", veriBirimi: "kg / ton", isoKategori: "CAT4", grupCode: "ATIK_BERTARAF" },
] as const;
