/* Denetim eylem etiketleri — sayfa ve CSV export ortak kullanır */
export const ACTION_LABELS: Record<string, { label: string; tone: "leaf" | "warm" | "gray" | "danger" }> = {
  GIRIS: { label: "giriş", tone: "gray" },
  GIRIS_BASARISIZ: { label: "başarısız giriş", tone: "danger" },
  CIKIS: { label: "çıkış", tone: "gray" },
  VERI_EKLE: { label: "veri girişi", tone: "leaf" },
  VERI_GUNCELLE: { label: "veri güncelleme", tone: "leaf" },
  VERI_SIL: { label: "veri silme", tone: "danger" },
  VERI_ONAYLA: { label: "onay", tone: "leaf" },
  VERI_TOPLU_ONAY: { label: "toplu onay", tone: "leaf" },
  CHAT_VERI_EKLE: { label: "asistan veri girişi", tone: "leaf" },
  CHAT_VERI_ONAY: { label: "asistan onayı", tone: "leaf" },
  VERI_ONAY_GERI_AL: { label: "onay geri alma", tone: "warm" },
  VERI_ICE_AKTAR: { label: "excel içe aktarım", tone: "leaf" },
  VERI_ANOMALI_ONAY: { label: "anomali doğrulama", tone: "warm" },
  TESIS_EKLE: { label: "tesis oluşturma", tone: "leaf" },
  TESIS_GUNCELLE: { label: "tesis güncelleme", tone: "leaf" },
  TESIS_SIL: { label: "tesis silme", tone: "danger" },
  FAKTOR_EKLE: { label: "faktör tanımı", tone: "leaf" },
  FAKTOR_GUNCELLE: { label: "faktör güncelleme", tone: "leaf" },
  FAKTOR_SIL: { label: "faktör silme", tone: "danger" },
  MAHALLE_EKLE: { label: "mahalle ekleme", tone: "leaf" },
  MAHALLE_GUNCELLE: { label: "mahalle güncelleme", tone: "leaf" },
  MAHALLE_SIL: { label: "mahalle silme", tone: "danger" },
  KENT_VERI_EKLE: { label: "kent verisi", tone: "leaf" },
  KENT_VERI_GUNCELLE: { label: "kent verisi güncelleme", tone: "leaf" },
  KENT_VERI_SIL: { label: "kent verisi silme", tone: "danger" },
  EYLEM_EKLE: { label: "eylem planı", tone: "leaf" },
  EYLEM_GUNCELLE: { label: "eylem güncelleme", tone: "leaf" },
  EYLEM_SIL: { label: "eylem silme", tone: "danger" },
  EYLEM_ILERLEME: { label: "ilerleme kaydı", tone: "leaf" },
  EYLEM_ILERLEME_GUNCELLE: { label: "ilerleme güncelleme", tone: "leaf" },
  EYLEM_ILERLEME_SIL: { label: "ilerleme silme", tone: "danger" },
  SENARYO_KAYDET: { label: "senaryo", tone: "leaf" },
  SENARYO_GUNCELLE: { label: "senaryo güncelleme", tone: "leaf" },
  SENARYO_SIL: { label: "senaryo silme", tone: "danger" },
  HEDEF_KAYDET: { label: "hedef", tone: "leaf" },
  HEDEF_SIL: { label: "hedef kaldırma", tone: "warm" },
  KURUM_AYAR: { label: "kurum ayarı", tone: "warm" },
  KURUM_OLUSTUR: { label: "kurum oluşturma", tone: "warm" },
  KURUM_GUNCELLE: { label: "kurum güncelleme", tone: "warm" },
  KURUM_SIL: { label: "kurum silme", tone: "danger" },
  KULLANICI_OLUSTUR: { label: "kullanıcı oluşturma", tone: "warm" },
  KULLANICI_GUNCELLE: { label: "kullanıcı güncelleme", tone: "warm" },
  KULLANICI_SIL: { label: "kullanıcı silme", tone: "danger" },
  PAROLA_DEGISTIR: { label: "parola değişimi", tone: "warm" },
  DENETIM_EXPORT: { label: "denetim dışa aktarım", tone: "gray" },
  RAPOR_PDF: { label: "pdf raporu", tone: "gray" },
  RAPOR_EXCEL: { label: "excel raporu", tone: "gray" },
  RAPOR_KENT: { label: "kent raporu", tone: "gray" },
  SISTEM_YEDEK: { label: "yedek indirme", tone: "warm" },
};
